apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    spec:
      metadata:
        labels:
          app: nginx
      containers:
        - name: nginx
          image: nginx:1.16.1
          ports:
          - containerPort: 80
