---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-server-deployment
spec:
  template:
    spec:
      containers:
      - name: simple-server
        image: ghcr.io/gagessele/simple-server:main